### ISSUE TITLE
ImportError: No module named 'domain'

### ISSUE THREAD

**Issue by roipoussiere** [bronto/javasphinx#51]
Javasphinx do not work on Python3 for me.

I use a virtual environnement:
```
$pyvenv venv
$source venv/bin/activate
```

I am actually on Python3:
```
$python -V
Python 3.4.3+
```

I installed javasphinx successfully:
```
$ pip install javasphinx
Successfully installed javasphinx javalang lxml beautifulsoup4 six
```

This is the installed packages:
```
$ pip freeze
beautifulsoup4==4.5.1
javalang==0.10.0
javasphinx==0.9.13
lxml==3.6.4
six==1.10.0
```

And this is the result of `javasphinx-apidoc` command (no matter the arguments I use):
```
$javasphinx-apidoc
Traceback (most recent call last):
  File "/home/nathanael/zest-writer/doc/vv/bin/javasphinx-apidoc", line 9, in <module>
    load_entry_point('javasphinx==0.9.13', 'console_scripts', 'javasphinx-apidoc')()
  File "/home/nathanael/zest-writer/doc/vv/lib/python3.4/site-packages/pkg_resources/__init__.py", line 558, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/nathanael/zest-writer/doc/vv/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2682, in load_entry_point
    return ep.load()
  File "/home/nathanael/zest-writer/doc/vv/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2355, in load
    return self.resolve()
  File "/home/nathanael/zest-writer/doc/vv/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2361, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/nathanael/zest-writer/doc/vv/lib/python3.4/site-packages/javasphinx/__init__.py", line 17, in <module>
    from domain import JavaDomain
ImportError: No module named 'domain'
```

I then tryed with a Python2 virtual env. and it works.

It's related to [this line](https://github.com/bronto/javasphinx/blob/master/javasphinx/__init__.py#L17) (I don't know why the init file don't see the `domain` module.).

System: Ubuntu 15.10

**Comment by c2nes** [comment]
Could you try upgrading to javasphinx 0.9.14 (just released). Those Python 3 changes were in master, but hadn't been released yet.

**Comment by roipoussiere** [comment]
It worked, thank you!

Note that I manually installed with pip the packages `docutils` and `sphinx`.

**Comment by c2nes** [comment]
Great! Glad that fixed things
