### ISSUE TITLE
How i can specific encoding for javasphinx-apidoc output?

### ISSUE THREAD

**Issue by isccarrasco** [bronto/javasphinx#56]
I have a java project, where my java files use the "UTF-8" encoding, 'cause the comments on some classes are writted on spanish using accents.

When i run the command.

``javasphinx-apidoc -o docs/java ~/Development/Projects/code/java -f -v``

always return the follow error:

    Traceback (most recent call last):
        File "/Users/user/Development/Projects/Docs/sphinx/myenv/bin/javasphinx-apidoc", line 11, in <module>sys.exit(main())
        File "/Users/user/Development/Projects/Docs/sphinx/myenv/lib/python2.7/site-packages/javasphinx/apidoc.py", line 317, in main write_documents(documents, sources, opts)
        File "/Users/user/Development/Projects/Docs/sphinx/myenv/lib/python2.7/site-packages/javasphinx/apidoc.py", line 112, in write_documents f.write(document)
        UnicodeEncodeError: 'ascii' codec can't encode character u'\xe1' in position 1464: ordinal not in range(128)

I wanto to specific the encoding of the files for the apidoc can write this files using utf-8.

is this possible?

[i asked this question on SO in this thread](http://stackoverflow.com/q/40355061/2706056)

Thanks for your help.

**Comment by bramp** [comment]
I've hit the same problem, but I worked around it by changing line javasphinx/apidoc.py line 112, to be `f.write(document.encode('utf-8'))`.

**Comment by isccarrasco** [comment]
Thanks @bramp ... this solution is working for me...

**Comment by bramp** [comment]
This should perhaps be kept open until it is fixed properly. I don't know if my suggested fix is the right one (because I don't really know python, or the details of UTF-8 and python), but happy to send a PR with my fix.

**Comment by c2nes** [comment]
Just pushed a change to fix this. Thanks for opening up the issue.
